### ISSUE TITLE
Doesn't launch through Steam (Steam Deck)

### ISSUE THREAD

**Issue by KibSquib48** [santiagocezar/maniatic-launcher#1]
I added this app to steam to use on my deck but it won't launch through steam. It launches fine when I do it through the application menu in desktop mode

**Comment by santiagocezar** [comment]
Could you send a screenshot of the "Properties..." menu for the game?

I recall having issues launching it through Steam too, but I don't remember how I fixed it... 😅

**Comment by KibSquib48** [comment]
![image](https://user-images.githubusercontent.com/33189136/226052893-8023ed13-fcd7-43aa-ab50-5784e553056f.png)

here's the full launch options: `"run" "--branch=beta" "--arch=x86_64" "--command=maniatic" "io.github.santiagocezar.maniatic-launcher"`

**Comment by KibSquib48** [comment]
do I need to change the "start in" path to the folder my Data.rsdk is in?

**Comment by santiagocezar** [comment]
maybe... does removing the `"--branch=beta"` arg do something?

**Comment by KibSquib48** [comment]
removing `--branch=beta` did nothing but changing the "start in" path to the Data.rsdk path did work
