### ISSUE TITLE
Encore

### ISSUE THREAD

**Issue by StuffOfSonny** [santiagocezar/maniatic-launcher#2]
I can't figure out how to get the mod that uses Steam APIs to enable the DLC to work [https://gamebanana.com/mods/397820].
I also can't figure out how to manually compile the decomp myself to enable the DLC, as I am on a Steam Deck.

**Comment by santiagocezar** [comment]
Yeah, that mod is Windows only so yeah, I had a PR open for that but it went nowhere, sadly.

Does the Steam Deck have flatpak-builder installed? If so you could simply download the [flatpak manifest](https://github.com/flathub/io.github.santiagocezar.maniatic-launcher) and compile with that, as it is essentially an automatic compilation script. You have to modify the `io.github.santiagocezar.maniatic-launcher.yaml` to disable the flag that disables the DLC, *but only if you already own it on Steam*.

Then to build it run:
```
flatpak-builder --force-clean build-dir io.github.santiagocezar.maniatic-launcher.yaml
```

And to install it:
```
flatpak build-export repo build-dir/
flatpak install --reinstall ./repo io.github.santiagocezar.maniatic-launcher
```

**Comment by santiagocezar** [comment]
and if it's not installed I think `flatpak-builder` also comes as a flatpak too, but I never tried it

**Comment by StuffOfSonny** [comment]
Unfortunately, neither appear to be the case. I will attempt to build the flatpak from the modified yaml from my laptop (then send it to my deck) tomorrow.

**Comment by StuffOfSonny** [comment]
"Failed to download sources: module mania: Can't find file at ogl-shader-mod.ini"

**Comment by santiagocezar** [comment]
Oh, did you open the terminal inside the folder you downloaded?

**Comment by StuffOfSonny** [comment]
I didn't download a folder, I downloaded the .yaml and then ran the commands from my downloads folder

**Comment by StuffOfSonny** [comment]
I see my mistake.

**Comment by StuffOfSonny** [comment]
![image](https://github.com/santiagocezar/maniatic-launcher/assets/61560546/5873cffd-af26-4c9c-ab9c-f1c36f7c66b6)
Thank you

**Comment by santiagocezar** [comment]
You're welcome!

**Comment by ghost** [comment]
> You have to modify the `io.github.santiagocezar.maniatic-launcher.yaml` to disable the flag that disables the DLC, _but only if you already own it on Steam_.

Hello there!
How can I activate the DLC if I don't own the Steam version and have the data.rsdk ripped from some other source?
