### ISSUE TITLE
Mod install instructions

### ISSUE THREAD

**Issue by Shy** [santiagocezar/maniatic-launcher#3]
This makes the game run amazingly on my steam deck. I'm wondering if you have a recommended mod manager or way of installing mods?

**Comment by santiagocezar** [comment]
i'm glad :D!!! 

not really, but now that you've asked i'm adding a handler for the 1-Click Install button from gamebanana, nothing fancy tho, but hopefully helpful!

**Comment by santiagocezar** [comment]
finally got back home and managed to get it working!

it works for simple mods like [this cool hud](https://gamebanana.com/mods/417773) 
![imagen](https://github.com/santiagocezar/maniatic-launcher/assets/48573316/d3655d54-62b7-45a7-a8b5-00476468e372)

but not with mods like [Extra Slot Amy](https://gamebanana.com/wips/50006), which are apparently source mods, you would need to modify and compile the flatpak yourself

**Comment by Shy** [comment]
Just tried it and it works great. 🤩

I'm now realizing that I can only run the launcher in desktop mode but not the gaming mode in the steam deck. Any ideas on this one?

**Comment by santiagocezar** [comment]
hm, does it work when launching it from steam in desktop mode? maybe it's related to #1

**Comment by Shy** [comment]
For whatever reason when I do the add to steam right click from the Deck destkop ui it sets the launch as my home directory. I updated it to the install location as outlined in #1 and that fixed it. No idea why the default add to steam function doesn't work here, but otherwise it's good to go.
